services:
  angular-frontend:
    build: .
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - API_BASE_URL=https://python-flask-0ni5.onrender.com
    restart: unless-stopped
